#ifndef GUARD_CONSTANTS_CHARACTER_NAMES_H
#define GUARD_CONSTANTS_CHARACTER_NAMES_H

#define CHAR_NAME_PLAYER 0
#define CHAR_NAME_PROF_BIRCH 1
#define CHAR_NAME_COUNT 2

#endif // GUARD_CONSTANTS_CHARACTER_NAMES_H